# Generated by Django 4.2.7 on 2023-12-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_gender_student_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='user',
        ),
    ]
