# Generated by Django 4.2.7 on 2023-12-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
