# Generated by Django 4.2.7 on 2024-06-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='f_name',
        ),
    ]
