# Generated by Django 4.2.7 on 2024-06-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_student_f_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
